=== mauriarroqui/raml-java-parser/raml-parser-2/src/test/resources/org/raml/v2/parser/api-rp-590/ref/supplier/shipment-ticket-request-schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"description": "Representation of a ticket request for multiple companies based on the shipment attributes of the purchase order.",
	"type": "object",
	"additionalProperties": false,
	"required": [
		"supplierNumber",
		"classificationNumber",
		"codeNumber",
		"serialNumber",
		"shipmentNumber",
		"ticketRequestReason"
	],
	"properties": {
		"supplierNumber": {
			"type": "integer",
			"description": "The merchandise supplier number",
			"minimum": 0,
			"maximum": 99999
		},
		"classificationNumber": {
			"type": "integer",
			"description": "The classification number",
			"minimum": 0,
			"maximum": 999
		},
		"codeNumber": {
			"type": "integer",
			"description": "The code number",
			"minimum": 0,
			"maximum": 99
		},
		"serialNumber": {
			"type": "integer",
			"description": "The serial number",
			"minimum": 0,
			"maximum": 999
		},
		"shipmentNumber": {
			"type": "integer",
			"description": "The shipment number",
			"minimum": 0,
			"maximum": 999
		},
		"masterCompanyIsoCodes": {
			"type": "array",
			"minItems": 1,
			"description": "List of master companies that are relevant for the request",
			"items": {
				"type": "string",
				"description": "The country iso code",
				"minLength": 2,
				"maxLength": 2,
				"pattern": "^[A-Z]{2}$",
				"examples": [
					"DE"
				]
			}
		},
		"allMasterCompanies": {
			"type": "boolean",
			"description": "This flag indicates that all master companies of the purchase order are requested (when true no masterCompanyIsoCodes must be set)"
		},
		"ticketRequestReason": {
			"type": "string",
			"description": "The ticket request reason",
			"enum": [
				"FirstRequest",
				"AddOnRequest",
				"PriceChangeDown",
				"PriceChangeUp",
				"CountryReAllocation",
				"OrderNumberChange",
				"TicketInfoChange"
			]
		},
		"requestedTicketType": {
			"type": "integer",
			"description": "The requested ticket type (only relevant for TAO users)",
			"minimum": 0,
			"maximum": 32767
		},
		"creationTimestamp": {
			"description": "User defined timestamp at which the request was created by the ticket provider",
			"type": "string",
			"format": "datetime"
		}
	}
}

=== mauriarroqui/raml-java-parser/raml-parser-2/src/test/resources/org/raml/v2/parser/api-rp-590/ref/supplier/shipment-ticket-request-example.json
{
	"supplierNumber": 99999,
	"classificationNumber": 999,
	"codeNumber": 99,
	"serialNumber": 999,
	"shipmentNumber": 999,
	"masterCompanyIsoCodes": [
		"DE",
		"NL",
		"FR"
	],
	"allMasterCompanies": false,
	"requestedTicketType": 105,
	"ticketRequestReason": "FirstRequest",
	"creationTimestamp": "2018-12-31T23:59:59.999Z"
}
