=== mauriarroqui/raml-java-parser/raml-parser-2/src/test/resources/org/raml/v2/parser/api-rp-590/ref/supplier/ticket-print-information-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Representation of the ticket print information (with 'preformatted' values)",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "ticketRequestId",
    "responseCode",
    "responseType"
  ],
  "properties": {
    "ticketRequestId": {
      "type": "string",
      "description": "The ticket request id. (generated during the creation of ticket print information)",
      "minimum": 32,
      "maximum": 32
    },
    "responseCode": {
      "type": "integer",
      "description": "The response code from the validation process",
      "minimum": 0,
      "maximum": 99999
    },
    "responseType": {
      "type": "string",
      "description": "The response type from the validation process ('Info' indicates that there were no issues during processing)",
      "enum": [
        "Info",
        "Warning",
        "Error"
      ]
    },
    "responseMessage": {
      "type": "string",
      "description": "The detailed response message from the validation process",
      "minLength": 1,
      "maxLength": 500
    },
    "ticketType": {
      "type": "integer",
      "description": "The ticket type being produced.",
      "minimum": 0,
      "maximum": 9999
    },
    "oekotexFlag": {
      "type": "boolean",
      "description": "Indicates whether it deals about oeko merchandise or not."
    },
    "nosSeasonIndicator": {
      "type": "string",
      "description": "The nos season indicator",
      "minLength": 1,
      "maxLength": 4
    },
    "orderNumber": {
      "type": "string",
      "description": "The order number",
      "minLength": 16,
      "maxLength": 16
    },
    "purchaseOrderNumber": {
      "type": "integer",
      "description": "The purchase order number corresponding to the parameters of the ticket request.",
      "minimum": 1,
      "maximum": 9999999999
    },
    "masterCompanies": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "companyIsoCode",
          "itemNumber",
          "sellingPrices",
          "colourSizes"
        ],
        "properties": {
          "companyIsoCode": {
            "type": "string",
            "description": "The country iso code is the identifier of a master company",
            "minLength": 2,
            "maxLength": 2,
            "pattern": "^[A-Z]{2}$",
            "examples": [
              "DE"
            ]
          },
          "ticketInfoText": {
            "type": "string",
            "description": "Information that might be printed on the ticket",
            "minLength": 1,
            "maxLength": 20
          },
          "customerSizeRange": {
            "type": "string",
            "description": "The customer size range",
            "minLength": 1,
            "maxLength": 15
          },
          "itemNumber": {
            "type": "string",
            "description": "The item number with leading zeroes",
            "minLength": 8,
            "maxLength": 8
          },
          "nationalStyleIdPrefix": {
            "type": "string",
            "description": "The national style identifier prefix",
            "minLength": 1,
            "maxLength": 4
          },
          "sellingPrices": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "companyIsoCode",
                "sellingPrice",
                "currencyCode",
                "printedCompanyIdentifier",
                "sellingPriceTicketPosition"
              ],
              "properties": {
                "companyIsoCode": {
                  "type": "string",
                  "description": "The country iso code of the respective country",
                  "minLength": 2,
                  "maxLength": 2,
                  "pattern": "^[A-Z]{2}$",
                  "examples": [
                    "DE"
                  ]
                },
                "sellingPrice": {
                  "type": "string",
                  "description": "The selling price",
                  "minLength": 4,
                  "maxLength": 8
                },
                "currencyCode": {
                  "type": "string",
                  "description": "The currency code",
                  "minLength": 1,
                  "maxLength": 5
                },
                "printedCompanyIdentifier": {
                  "type": "string",
                  "description": "The printed company identifier",
                  "minLength": 1,
                  "maxLength": 2
                },
                "sellingPriceTicketPosition": {
                  "type": "integer",
                  "description": "The selling price position on the ticket",
                  "minimum": 1,
                  "maximum": 2
                },
                "licensePlateCompanyIdentifier": {
                  "type": "string",
                  "description": "The license plate company identifier",
                  "minLength": 2,
                  "maxLength": 2,
                  "pattern": "^[A-Z]{2}$",
                  "examples": [
                    "DE"
                  ]
                }
              }
            }
          },
          "colourSizes": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "colourTicketPositionNumber",
                "computerSizeNumber",
                "quantity",
                "barcode",
                "barcodeSubLine"
              ],
              "properties": {
                "colourTicketPositionNumber": {
                  "type": "string",
                  "description": "The colour ticket position number",
                  "minLength": 1,
                  "maxLength": 1
                },
                "computerSizeNumber": {
                  "type": "string",
                  "description": "The computer size number",
                  "minLength": 3,
                  "maxLength": 3
                },
                "quantity": {
                  "type": "integer",
                  "description": "The quantity of a colour size combination",
                  "minimum": 1,
                  "maximum": 999999
                },
                "pantoneName": {
                  "type": "string",
                  "description": "The pantone name of the colour",
                  "minLength": 1,
                  "maxLength": 70
                },
                "colourDescription": {
                  "type": "string",
                  "description": "The colour description",
                  "minLength": 1,
                  "maxLength": 60
                },
                "customerSizeNumber": {
                  "type": "string",
                  "description": "The customer size number of that specific small company",
                  "minLength": 1,
                  "maxLength": 7
                },
                "additionalSizeInformation": {
                  "type": "string",
                  "description": "An additional size information",
                  "minLength": 1,
                  "maxLength": 12
                },
                "gtin": {
                  "type": "string",
                  "description": "The Global Trade Item Number",
                  "minLength": 16,
                  "maxLength": 16
                },
                "url": {
                  "type": "string",
                  "format": "uri",
                  "description": "The URI to the product in the C and A online shop (used for the 2D barcode)",
                  "minLength": 1,
                  "maxLength": 500
                },
                "barcode": {
                  "type": "object",
                  "additionalProperties": false,
                  "required": [
                    "lineIdentifier",
                    "itemNumber",
                    "colourTicketPositionNumber",
                    "computerSizeNumber"
                  ],
                  "properties": {
                    "lineIdentifier": {
                      "type": "string",
                      "description": "The line identifier",
                      "minLength": 1,
                      "maxLength": 2
                    },
                    "itemNumber": {
                      "type": "string",
                      "description": "The item number",
                      "minLength": 7,
                      "maxLength": 7
                    },
                    "colourTicketPositionNumber": {
                      "type": "string",
                      "description": "The colour ticket position number",
                      "minLength": 1,
                      "maxLength": 1
                    },
                    "computerSizeNumber": {
                      "type": "string",
                      "description": "The computer size number",
                      "minLength": 3,
                      "maxLength": 3
                    }
                  }
                },
                "barcodeSubLine": {
                  "type": "object",
                  "additionalProperties": false,
                  "required": [
                    "lineIdentifier",
                    "itemNumber",
                    "colourTicketPositionNumber",
                    "computerSizeNumber"
                  ],
                  "properties": {
                    "lineIdentifier": {
                      "type": "string",
                      "description": "The line identifier",
                      "minLength": 1,
                      "maxLength": 2
                    },
                    "itemNumber": {
                      "type": "string",
                      "description": "The item number",
                      "minLength": 8,
                      "maxLength": 8
                    },
                    "colourTicketPositionNumber": {
                      "type": "string",
                      "description": "The colour ticket position number",
                      "minLength": 1,
                      "maxLength": 1
                    },
                    "computerSizeNumber": {
                      "type": "string",
                      "description": "The computer size number",
                      "minLength": 3,
                      "maxLength": 3
                    }
                  }
                },
                "waistbandRiderCode": {
                  "type": "integer",
                  "description": "The code for the waistband rider",
                  "minimum": 0,
                  "maximum": 99
                },
                "waistbandRiderColour": {
                  "type": "string",
                  "description": "The colour of the waistband rider",
                  "minLength": 1,
                  "maxLength": 32
                },
                "waistbandRiderText": {
                  "type": "string",
                  "description": "The text for the waistband rider",
                  "minLength": 1,
                  "maxLength": 35
                }
              }
            }
          }
        }
      }
    }
  }
}

=== mauriarroqui/raml-java-parser/raml-parser-2/src/test/resources/org/raml/v2/parser/api-rp-590/ref/supplier/ticket-print-information-example.json
{
  "ticketRequestId": "567a5eae74d543bcadbfeb165c37a0e6",
  "responseCode": 0,
  "responseType": "Info",
  "responseMessage": "No error occured during validation",
  "ticketType": 105,
  "oekotexFlag": true,
  "nosSeasonIndicator": "SNOS",
  "orderNumber": "705/32/77580/656",
  "purchaseOrderNumber": 80792995,
  "masterCompanies": [
    {
      "companyIsoCode": "AT",
      "itemNumber": "0123.456",
      "ticketInfoText": "CB:07_THEM _PR_TA02",
      "nationalStyleIdPrefix": "S820",
      "customerSizeRange": "XS - XXL",
      "sellingPrices": [
        {
          "companyIsoCode": "AT",
          "sellingPrice": "8.00",
          "currencyCode": "EURO",
          "sellingPriceTicketPosition": 1,
          "printedCompanyIdentifier": "A",
          "licensePlateCompanyIdentifier": "AT"
        },
        {
          "companyIsoCode": "RO",
          "sellingPrice": "34.90",
          "currencyCode": "RON",
          "sellingPriceTicketPosition": 2,
          "printedCompanyIdentifier": "RO",
          "licensePlateCompanyIdentifier": "RO"
        }
      ],
      "colourSizes": [
        {
          "colourTicketPositionNumber": "1",
          "computerSizeNumber": "056",
          "quantity": 150,
          "pantoneName": "16-5803",
          "colourDescription": "Flint Gray",
          "customerSizeNumber": "M",
          "additionalSizeInformation": "0-1 MON",
          "gtin": "04 061507 789603",
          "url": "https://qr.c-a.com/?01=04061507789603",
          "barcode": {
            "lineIdentifier": "A",
            "itemNumber": "0123456",
            "colourTicketPositionNumber": "1",
            "computerSizeNumber": "056"
          },
          "barcodeSubLine": {
            "lineIdentifier": "A",
            "itemNumber": "0123.456",
            "colourTicketPositionNumber": "1",
            "computerSizeNumber": "056"
          },
          "waistbandRiderCode": 13,
          "waistbandRiderColour": "yellow",
          "waistbandRiderText": "WEITE PASSWORM"
        }
      ]
    }
  ]
}
